[package]
name = "day04"
version = "0.1.0"
authors = ["tarpaha <ppopchikovsky@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
semaphore = "0.4.0"
num_cpus = "1.13.0"
md-5 = "0.9.1"
utils = { path = "../utils" }